# Generated by Django 2.2.1 on 2019-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('usuario', models.CharField(default='', max_length=50)),
               ('senha', models.CharField(default='', max_length=50)),
            ],
            options={
                'ordering': ('usuario',),
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),

        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('titulo', models.TextField()),
                ('conteudo', models.TextField()),
            ],
        ),


    ]
